# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
resources:
  pipelines:
  - pipeline: security-lib
    source: Test_predict
    trigger: 
      branches:
      - releases/*
      - master

pool:
  vmImage: 'ubuntu-latest'


steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(ls)'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '1dc5124d-c084-4343-bb4f-87b88e7d2eb6'
    definition: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: './'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(ls test)'
