# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


resources:
  pipelines:
    - pipeline: Test
      project: Test
      source: test
      trigger:     # optional; Triggers are not enabled by default.
        branches:  
          include: [master]      


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '1dc5124d-c084-4343-bb4f-87b88e7d2eb6'
    definition: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: './'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '1dc5124d-c084-4343-bb4f-87b88e7d2eb6'
    definition: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Agent.BuildDirectory)'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'cp $(Agent.BuildDirectory)/test/* ./'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(ls)'
